# Generated by Django 2.2.5 on 2020-09-02 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShortLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('short_url', models.CharField(max_length=100)),
                ('long_url', models.CharField(max_length=500)),
            ],
        ),
    ]
